name: Build and Deploy

on:
  push:
    branches: [ master ]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # 更新到 Node.js 18
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        env:
          NODE_OPTIONS: '--experimental-global-webcrypto --no-warnings'
          VITE_CJS_IGNORE_WARNING: true
        run: npm run build
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vue-system:latest
          
      - name: Trigger webhook
        run: |
          curl -X POST "http://104.131.187.248:25718/hook?access_key=oK7Q2rhPcjrH7nQ1GJE5EDKrkYBEczvy9KTiSIhyvTSbKcqh&params=aaa"
